version: 2

jobs:
  bionic:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build -c release
      - run: swift test -c release
  bionic-release:
    docker:
      - image: swift:5.0-bionic
    steps:
      - checkout
      - run: swift build -c release
  xenial:
    docker:
      - image: swift:5.0-xenial
    steps:
      - checkout
      - run: swift build -c release
      - run: swift test -c release
  xenial-release:
    docker:
      - image: swift:5.0-xenial
    steps:
      - checkout
      - run: swift build -c release

workflows:
  version: 2
  tests:
    jobs:
      - bionic
      - bionic-release
      - xenial
      - xenial-release
